### PR TITLE
My article on 'how to calculate a project'

### PR DESCRIPTION
**Pull request by aleron75**

### CODE REVIEW

**Comment by tobi-pb** [comment]
Thanks a lot :)  Could you give a s short about you text please? i will add it at the end of the page :)

**Comment by aleron75** [comment]
Hello Tobias,
here is a short bio:

Alessandro Ronchi works at Bitbull as lead Magento specialist, devoted to
software design and backend development.
He is an active contributor of the #realmagento community, author, trainer,
speaker and conference organizer.

Cheers,
Alessandro


Alessandro Ronchi
www.alessandroronchi.com
aleron75@gmail.com
@aleron75 <https://twitter.com/aleron75>

2016-12-10 18:50 GMT+01:00 Tobias Vogt <notifications@github.com>:

**Comment by tobi-pb** [comment]
Hey Alessandro,

thanks for your blog-post, very interesting. You you give me a short about you text and a small picture? I will add it at the end of your post

**Comment by tobi-pb** [comment]
Sorry, haven't seen your answer :-D

**Comment by aleron75** [comment]
Hello Tobias,
you can download a profile picutre here:

*https://it.gravatar.com/userimage/21879898/bb41a89ca601b5a62dec46c8c9861f97.png?size=256
<https://it.gravatar.com/userimage/21879898/bb41a89ca601b5a62dec46c8c9861f97.png?size=256>*

Cheers,
Alessandro

Alessandro Ronchi
www.alessandroronchi.com
aleron75@gmail.com
@aleron75 <https://twitter.com/aleron75>

2016-12-12 21:15 GMT+01:00 Tobias Vogt <notifications@github.com>:

**Pull request merged**
